version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  livekit:
    image: livekit/livekit-server:latest
    secrets:
      - source: certificate_crt
        target: certificate.crt
      - source: certificate_key
        target: certificate.key
    configs:
      - source: livekit_config
        target: /livekit/livekit.yaml
        mode: 0444
    command: --config /livekit/livekit.yaml
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - redis
      - mongo

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  
  livekit-ingress:
    image: livekit/ingress:latest
    environment:
      INGRESS_CONFIG_BODY: |
        api_key:APIXMCTJEXDBghU
        api_secret:laxpDMZwSmNlxvjHzG8YnZsti8ofCMRlY9H6OAL7EeL
        ws_url: "wss://onliver.ru:8080/livekit"
        redis:
          address: "onliver.ru:6379"     
        rtmp_port: 1935
        whip_port: 8001
        health_port: 9000
        logging:
          level: debug
        rtc_config:
          use_external_ip: true
        resource_requirements: 
          cpu:
            min: 1.0
            recommended: 2.0
          rtmp:
            min: 1
            recommended: 2
        cpu_cost:
          rtmp_cpu_cost: 2
          whip_cpu_cost: 2
          whip_bypass_transcoding_cpu_cost: 2
          url_cpu_cost: 2
          url: 2
        
    ports:
      # RTMP порт
      - target: 1935
        published: 1935
        protocol: tcp
        mode: host
      # WHIP порт, согласно требованию – публикуем на 8001
      - target: 8001
        published: 8001
        protocol: tcp
        mode: host
      # Порт для health-check (опционально)
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - redis
      - livekit

configs:
  livekit_config:
    file: config/livekit/livekit.yaml

secrets:
  certificate_crt:
    file: config/livekit/certificate.crt
  certificate_key:
    file: config/livekit/certificate.key

volumes:
  mongo_data:
  minio_data:
  redis_data:

networks:
  host-network:
    external: true
    name: host