version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  livekit:
    image: livekit/livekit-server:latest
    secrets:
      - source: certificate_crt
        target: certificate.crt
      - source: certificate_key
        target: certificate.key
    configs:
      - source: livekit_config
        target: /livekit/livekit.yaml
        mode: 0444
    command: --config /livekit/livekit.yaml
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - redis
      - mongo

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - host-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

configs:
  livekit_config:
    file: config/livekit/livekit.yaml

secrets:
  certificate_crt:
    file: config/livekit/certificate.crt
  certificate_key:
    file: config/livekit/certificate.key

volumes:
  mongo_data:
  minio_data:
  redis_data:

networks:
  host-network:
    external: true
    name: host