port: 7880
log_level: info

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: onliver.ru:6379

keys:
  APIXMCTJEXDBghU: laxpDMZwSmNlxvjHzG8YnZsti8ofCMRlY9H6OAL7EeL


turn:
  enabled: true
  udp_port: 3478
  tls_port: 5349
  domain: "onliver.ru"
  external_tls: true
  cert_file: /run/secrets/certificate.crt
  key_file: /run/secrets/certificate.key


  