name: CI/CD Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Остановка работающего стека и удаление старого образа
      - name: Stop running stack and remove old image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN  }}
            echo "Stopping existing stack..."
            sudo docker stack rm onliver_infrastructure_stack || true
            sudo docker stack rm onliver_infrastructure_livekit_stack || true
            echo "Waiting for the stack to stop..."

      # Удаляем существующий deploy на сервере с использованием sudo
      - name: Remove existing deploy on remote host
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Удаляем старый deploy с использованием sudo..."
            sudo rm -rf deploy

      # Передача файла deploy на удалённый сервер
      - name: Copy 'deploy' Directory to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'deploy/*'
          target: '~/'

      # Подключение по SSH, авторизация в Docker Hub на сервере и деплой нового стека
      - name: Deploy new stack
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Logging in to Docker Hub on remote host..."
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN  }}
            echo "Deploying new stack..."
            ls
            sudo docker stack deploy --detach=true -c ~/deploy/docker-compose1.yaml onliver_infrastructure_stack
            sudo docker stack deploy --detach=true -c ~/deploy/docker-compose2.yaml onliver_infrastructure_livekit_stack
